### ISSUE TITLE
Message spam when streaming music

### ISSUE THREAD

**Issue by Swyreee** [nameless-on-discord/nameless#16]
**Describe the bug**
Title.

**To Reproduce**
1. Tell bot to connect to a voice channel
2. Play a stream using `/music radio`
3. Wait when the stream briefly disconnects.
4. Profit!

**Expected behavior**
The "Streaming music from ..." is sent only once. 

**Screenshots**
N/A

**Additional context**
N/A

**Comment by FoxeiZ** [comment]
Bug chỉ ảnh hưởng đến lavalink à? Hay logic có cần chỉnh bên native luôn không

**Comment by Swyreee** [comment]
Chắc là có ấy: https://github.com/nameless-on-discord/nameless/blob/main/nameless/cogs/MusicNativeCog.py#L121-122
